### ISSUE TITLE
filetime 기반 기술 조사

### ISSUE THREAD

**Issue by arsgsg1** [0xF4D3C0D3/Project2#3]
filetime 기반 기술 조사

**Comment by 0xF4D3C0D3** [comment]
- localtime(): time_t값을 활용할 수 있게 가공시켜주는 함수

```c
#include <time.h>

struct tm *localtime(const time_t* timep);
```

- const time_t* timep: time_t형 변수를 가리키는 포인터
- struct tm* localtime: 시간 정보가 들어가는 구조체 포인터
- month의 경우 0부터 시작함(1월이 0으로 나타남)
