### ISSUE TITLE
timecmp 기반 기술 조사

### ISSUE THREAD

**Issue by arsgsg1** [0xF4D3C0D3/Project2#6]
timecmp 기반 기술 조사

**Comment by 0xF4D3C0D3** [comment]
#3 를 참고하면

localtime이라는 함수에 stat.st_mtime 필드를 넘겨 파일의 마지막 수정 시간을 받아올 수 있다.
이 시간은 struct tm* 타입으로 되어있는데 여기서 time->tm_hour, time->tm_min과 같은 형태로 시, 분 정보를 얻을 수 있다.

이를 이용해 대소관계를 비교하여 어떤 파일이 더 최근에 수정되었는지 확인하도록 한다.
